services:
  postgres:
    container_name: sew_reservations_postgres
    image: postgres:17-alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=reservations_password
      - POSTGRES_USER=reservations
      - POSTGRES_DB=reservations