GET {{BASE_URL}}/api/customer/health

###

POST {{BASE_URL}}/api/customer
Content-Type: application/json

{
"name": "John Doe",
"email": "johndoe@gmail.com",
"phone": "+43 677 1234567890",
"password": "password",
"street": "Street",
"city": "City",
"zip": "1234",
"country": "Country",
"houseNo": "1"
}
> {% client.global.set("cust_id", response.body.id); %}

###

GET {{BASE_URL}}/api/customer/{{cust_id}}

###

PUT {{BASE_URL}}/api/customer
Content-Type: application/json

{
"id": {{cust_id}},
"name": "John Doe 2",
"email": "johndoe2@gmail.com",
"phone": "+43 677 3987409",
"password": "password2",
"street": "Street2",
"city": "City2",
"zip": "12345",
"country": "Country2",
"houseNo": "2"
}

###

DELETE {{BASE_URL}}/api/customer/{{cust_id}}

###

POST {{BASE_URL}}/api/auth/login
Content-Type: application/json

{
  "userId": "johndoe",
  "password": "password"
}
> {% client.global.set("token", response.body.token); %}


###

GET http://localhost:8080/api/fields/list
Accept: application/json
Authorization: Bearer {{token}}